return {
    "nvim-treesitter/nvim-treesitter",
    opts = {
        ensure_installed = {
            "c",
            "lua",
            "rust",
            "javascript",
            "typescript",
            "svelte",
            "json",
            "toml",
            "regex",
            "tsx",
            "scss",
            "css",
            "go",
            "zig",
            "gitignore",
            "c_sharp",
            "cmake",
            "dockerfile",
            "git_config",
            "git_rebase",
            "gitattributes",
            "gitcommit",
            "graphql",
            "java",
            "html",
            "llvm",
            "prisma",
            "python",
            "sql",
            "yaml"
        },
    },
}
